include:
  - docker-compose-pi.yml

services:  
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_pw
      POSTGRES_USER: cazzubot
      POSTGRES_DB: main
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    secrets:
      - db_pw

  webapp:
    image: cazzubot
    stdin_open: true
    tty: true
    depends_on:
      - database
    volumes:
      - botlog:/mnt/bot_log
    command: 

volumes:
  pgdata:
  botlog:

secrets:
  db_pw:
    file: ./secret/db_pw
